/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountIdentifier = Uint8Array;
export type CycleCheckResult = { 'ok' : bigint } |
  { 'err' : string };
export interface CycleInfo { 'balance' : bigint, 'healthStatus' : HealthStatus }
export type CycleTopUpResult = { 'ok' : bigint } |
  { 'err' : string };
export type HealthStatus = { 'ok' : null } |
  { 'low' : null } |
  { 'critical' : null };
export interface OwnedCanister {
  'userName' : string,
  'created' : Time,
  'modified' : Time,
  'owner' : Principal,
  'canisterId' : Principal,
}
export interface PixelPurchase {
  'status' : PurchaseStatus,
  'txIndex' : bigint,
  'createdAt' : Time,
  'pixels' : bigint,
  'amountE8s' : bigint,
  'buyer' : Principal,
}
export interface Project {
  'id' : string,
  'owner' : Principal,
  'metadata' : ProjectMetadata,
  'data' : Uint8Array,
}
export interface ProjectMetadata {
  'created' : Time,
  'modified' : Time,
  'name' : string,
  'size' : bigint,
  'version' : bigint,
}
export type ProjectResult = { 'ok' : string } |
  { 'err' : string };
export type PurchaseStatus = { 'pending' : null } |
  { 'credited' : null };
export type Time = bigint;
export interface UserPersonalInfo {
  'name' : string,
  'email' : string,
  'additional' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addOwnedCustomer' : ActorMethod<[OwnedCanister], undefined>,
  'adminBanUser' : ActorMethod<[Principal], undefined>,
  'adminCreditPixels' : ActorMethod<[Principal, bigint, string], bigint>,
  'adminCreditPixelsForPurchase' : ActorMethod<
    [bigint, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'adminRemovePixels' : ActorMethod<[Principal, bigint, string], bigint>,
  'adminUnbanUser' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProject' : ActorMethod<[string], ProjectResult>,
  'getAdminUserOverview' : ActorMethod<
    [],
    Array<
      {
        'principal' : Principal,
        'name' : [] | [string],
        'email' : [] | [string],
        'pixels' : bigint,
      }
    >
  >,
  'getAllUserPixelBalances' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getAllUsersWithPersonalInfo' : ActorMethod<
    [],
    Array<
      [
        Principal,
        { 'name' : string, 'email' : string, 'additional' : [] | [string] },
      ]
    >
  >,
  'getCallerAccountIdentifier' : ActorMethod<[], string>,
  'getCallerICPBalance' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getCallerPixelBalance' : ActorMethod<[], bigint>,
  'getCallerPrincipal' : ActorMethod<[], Principal>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterCycleInfo' : ActorMethod<[], [] | [CycleInfo]>,
  'getCanisterCycles' : ActorMethod<[], CycleCheckResult>,
  'getCanisterHealthStatus' : ActorMethod<[], HealthStatus>,
  'getCurrentEra' : ActorMethod<[], string>,
  'getEditorVisitCount' : ActorMethod<[], bigint>,
  'getMyPendingPixelPurchases' : ActorMethod<[], Array<PixelPurchase>>,
  'getOwnedCustomerByCanister' : ActorMethod<[Principal], [] | [OwnedCanister]>,
  'getOwnedCustomersByUser' : ActorMethod<[Principal], Array<OwnedCanister>>,
  'getPersonalInfo' : ActorMethod<[], [] | [UserPersonalInfo]>,
  'getPixelPrice' : ActorMethod<[], bigint>,
  'getProject' : ActorMethod<[string], [] | [Project]>,
  'getRealBackendCycleInfo' : ActorMethod<[], [] | [CycleInfo]>,
  'getRealFrontendCycleInfo' : ActorMethod<[], [] | [CycleInfo]>,
  'getTotalPixelsSold' : ActorMethod<[], bigint>,
  'getTotalProjectCount' : ActorMethod<[], bigint>,
  'getUserPersonalInfo' : ActorMethod<[Principal], [] | [UserPersonalInfo]>,
  'getUserPixelBalance' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjectCount' : ActorMethod<[Principal], bigint>,
  'getUsersByName' : ActorMethod<
    [string],
    Array<[Principal, UserPersonalInfo]>
  >,
  'getUsersWithCompleteInfo' : ActorMethod<
    [],
    Array<[Principal, UserPersonalInfo]>
  >,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeDemoUserProfile' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserBanned' : ActorMethod<[Principal], boolean>,
  'listAllKnownUsers' : ActorMethod<[], Array<Principal>>,
  'listAllUsers' : ActorMethod<[], Array<Principal>>,
  'listAllUsersWithPersonalInfo' : ActorMethod<
    [],
    Array<[Principal, UserPersonalInfo]>
  >,
  'listOwnedCustomers' : ActorMethod<[], Array<OwnedCanister>>,
  'listPendingPixelPurchases' : ActorMethod<[], Array<PixelPurchase>>,
  'listProjects' : ActorMethod<[], Array<[string, ProjectMetadata]>>,
  'newProject' : ActorMethod<[string, Uint8Array], ProjectResult>,
  'recordEditorVisit' : ActorMethod<[], undefined>,
  'recordPixelPurchase' : ActorMethod<
    [bigint, bigint, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'removeOwnedCustomer' : ActorMethod<[Principal], undefined>,
  'requestControllerAccess' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePersonalInfo' : ActorMethod<[UserPersonalInfo], undefined>,
  'searchUsersByEmail' : ActorMethod<
    [string],
    Array<[Principal, UserPersonalInfo]>
  >,
  'setCurrentEra' : ActorMethod<[string], undefined>,
  'setCyclesThresholds' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'testAdminImport' : ActorMethod<[bigint], string>,
  'topUpCanisterCycles' : ActorMethod<[bigint], CycleTopUpResult>,
  'topUpFrontendCanisterCycles' : ActorMethod<[bigint], CycleTopUpResult>,
  'transferICP' : ActorMethod<
    [AccountIdentifier, bigint, [] | [bigint]],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'updateOwnedCustomer' : ActorMethod<[Principal, OwnedCanister], undefined>,
  'updateProject' : ActorMethod<[string, Uint8Array], ProjectResult>,
  'verifyIcpPayment' : ActorMethod<[bigint, Principal, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];