/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const OwnedCanister = IDL.Record({
  'userName' : IDL.Text,
  'created' : Time,
  'modified' : Time,
  'owner' : IDL.Principal,
  'canisterId' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const HealthStatus = IDL.Variant({
  'ok' : IDL.Null,
  'low' : IDL.Null,
  'critical' : IDL.Null,
});
export const CycleInfo = IDL.Record({
  'balance' : IDL.Nat,
  'healthStatus' : HealthStatus,
});
export const CycleCheckResult = IDL.Variant({
  'ok' : IDL.Nat,
  'err' : IDL.Text,
});
export const PurchaseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'credited' : IDL.Null,
});
export const PixelPurchase = IDL.Record({
  'status' : PurchaseStatus,
  'txIndex' : IDL.Nat,
  'createdAt' : Time,
  'pixels' : IDL.Nat,
  'amountE8s' : IDL.Nat,
  'buyer' : IDL.Principal,
});
export const UserPersonalInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'additional' : IDL.Opt(IDL.Text),
});
export const ProjectMetadata = IDL.Record({
  'created' : Time,
  'modified' : Time,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'version' : IDL.Nat,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'metadata' : ProjectMetadata,
  'data' : IDL.Vec(IDL.Nat8),
});
export const CycleTopUpResult = IDL.Variant({
  'ok' : IDL.Nat,
  'err' : IDL.Text,
});
export const AccountIdentifier = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  'addOwnedCustomer' : IDL.Func([OwnedCanister], [], []),
  'adminBanUser' : IDL.Func([IDL.Principal], [], []),
  'adminCreditPixels' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'adminCreditPixelsForPurchase' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'adminRemovePixels' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'adminUnbanUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [ProjectResult], []),
  'getAdminUserOverview' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'principal' : IDL.Principal,
            'name' : IDL.Opt(IDL.Text),
            'email' : IDL.Opt(IDL.Text),
            'pixels' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getAllUserPixelBalances' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getAllUsersWithPersonalInfo' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Principal,
            IDL.Record({
              'name' : IDL.Text,
              'email' : IDL.Text,
              'additional' : IDL.Opt(IDL.Text),
            }),
          )
        ),
      ],
      [],
    ),
  'getCallerAccountIdentifier' : IDL.Func([], [IDL.Text], []),
  'getCallerICPBalance' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat64, 'err' : IDL.Text })],
      [],
    ),
  'getCallerPixelBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerPrincipal' : IDL.Func([], [IDL.Principal], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterCycleInfo' : IDL.Func([], [IDL.Opt(CycleInfo)], []),
  'getCanisterCycles' : IDL.Func([], [CycleCheckResult], []),
  'getCanisterHealthStatus' : IDL.Func([], [HealthStatus], []),
  'getCurrentEra' : IDL.Func([], [IDL.Text], ['query']),
  'getEditorVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyPendingPixelPurchases' : IDL.Func(
      [],
      [IDL.Vec(PixelPurchase)],
      ['query'],
    ),
  'getOwnedCustomerByCanister' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(OwnedCanister)],
      [],
    ),
  'getOwnedCustomersByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(OwnedCanister)],
      [],
    ),
  'getPersonalInfo' : IDL.Func([], [IDL.Opt(UserPersonalInfo)], []),
  'getPixelPrice' : IDL.Func([], [IDL.Nat64], ['query']),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], []),
  'getRealBackendCycleInfo' : IDL.Func([], [IDL.Opt(CycleInfo)], []),
  'getRealFrontendCycleInfo' : IDL.Func([], [IDL.Opt(CycleInfo)], []),
  'getTotalPixelsSold' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalProjectCount' : IDL.Func([], [IDL.Nat], []),
  'getUserPersonalInfo' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserPersonalInfo)],
      ['query'],
    ),
  'getUserPixelBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjectCount' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'getUsersByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserPersonalInfo))],
      [],
    ),
  'getUsersWithCompleteInfo' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserPersonalInfo))],
      [],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeDemoUserProfile' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listAllKnownUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'listAllUsersWithPersonalInfo' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserPersonalInfo))],
      ['query'],
    ),
  'listOwnedCustomers' : IDL.Func([], [IDL.Vec(OwnedCanister)], []),
  'listPendingPixelPurchases' : IDL.Func(
      [],
      [IDL.Vec(PixelPurchase)],
      ['query'],
    ),
  'listProjects' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ProjectMetadata))],
      [],
    ),
  'newProject' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [ProjectResult], []),
  'recordEditorVisit' : IDL.Func([], [], []),
  'recordPixelPurchase' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'removeOwnedCustomer' : IDL.Func([IDL.Principal], [], []),
  'requestControllerAccess' : IDL.Func([], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePersonalInfo' : IDL.Func([UserPersonalInfo], [], []),
  'searchUsersByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserPersonalInfo))],
      [],
    ),
  'setCurrentEra' : IDL.Func([IDL.Text], [], []),
  'setCyclesThresholds' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'testAdminImport' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'topUpCanisterCycles' : IDL.Func([IDL.Nat], [CycleTopUpResult], []),
  'topUpFrontendCanisterCycles' : IDL.Func([IDL.Nat], [CycleTopUpResult], []),
  'transferICP' : IDL.Func(
      [AccountIdentifier, IDL.Nat64, IDL.Opt(IDL.Nat64)],
      [IDL.Variant({ 'ok' : IDL.Nat64, 'err' : IDL.Text })],
      [],
    ),
  'updateOwnedCustomer' : IDL.Func([IDL.Principal, OwnedCanister], [], []),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8)],
      [ProjectResult],
      [],
    ),
  'verifyIcpPayment' : IDL.Func(
      [IDL.Nat, IDL.Principal, IDL.Nat],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const OwnedCanister = IDL.Record({
    'userName' : IDL.Text,
    'created' : Time,
    'modified' : Time,
    'owner' : IDL.Principal,
    'canisterId' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const HealthStatus = IDL.Variant({
    'ok' : IDL.Null,
    'low' : IDL.Null,
    'critical' : IDL.Null,
  });
  const CycleInfo = IDL.Record({
    'balance' : IDL.Nat,
    'healthStatus' : HealthStatus,
  });
  const CycleCheckResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const PurchaseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'credited' : IDL.Null,
  });
  const PixelPurchase = IDL.Record({
    'status' : PurchaseStatus,
    'txIndex' : IDL.Nat,
    'createdAt' : Time,
    'pixels' : IDL.Nat,
    'amountE8s' : IDL.Nat,
    'buyer' : IDL.Principal,
  });
  const UserPersonalInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'additional' : IDL.Opt(IDL.Text),
  });
  const ProjectMetadata = IDL.Record({
    'created' : Time,
    'modified' : Time,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'version' : IDL.Nat,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'metadata' : ProjectMetadata,
    'data' : IDL.Vec(IDL.Nat8),
  });
  const CycleTopUpResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const AccountIdentifier = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    'addOwnedCustomer' : IDL.Func([OwnedCanister], [], []),
    'adminBanUser' : IDL.Func([IDL.Principal], [], []),
    'adminCreditPixels' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adminCreditPixelsForPurchase' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'adminRemovePixels' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adminUnbanUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [ProjectResult], []),
    'getAdminUserOverview' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'principal' : IDL.Principal,
              'name' : IDL.Opt(IDL.Text),
              'email' : IDL.Opt(IDL.Text),
              'pixels' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getAllUserPixelBalances' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getAllUsersWithPersonalInfo' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Principal,
              IDL.Record({
                'name' : IDL.Text,
                'email' : IDL.Text,
                'additional' : IDL.Opt(IDL.Text),
              }),
            )
          ),
        ],
        [],
      ),
    'getCallerAccountIdentifier' : IDL.Func([], [IDL.Text], []),
    'getCallerICPBalance' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat64, 'err' : IDL.Text })],
        [],
      ),
    'getCallerPixelBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerPrincipal' : IDL.Func([], [IDL.Principal], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterCycleInfo' : IDL.Func([], [IDL.Opt(CycleInfo)], []),
    'getCanisterCycles' : IDL.Func([], [CycleCheckResult], []),
    'getCanisterHealthStatus' : IDL.Func([], [HealthStatus], []),
    'getCurrentEra' : IDL.Func([], [IDL.Text], ['query']),
    'getEditorVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyPendingPixelPurchases' : IDL.Func(
        [],
        [IDL.Vec(PixelPurchase)],
        ['query'],
      ),
    'getOwnedCustomerByCanister' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(OwnedCanister)],
        [],
      ),
    'getOwnedCustomersByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OwnedCanister)],
        [],
      ),
    'getPersonalInfo' : IDL.Func([], [IDL.Opt(UserPersonalInfo)], []),
    'getPixelPrice' : IDL.Func([], [IDL.Nat64], ['query']),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], []),
    'getRealBackendCycleInfo' : IDL.Func([], [IDL.Opt(CycleInfo)], []),
    'getRealFrontendCycleInfo' : IDL.Func([], [IDL.Opt(CycleInfo)], []),
    'getTotalPixelsSold' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalProjectCount' : IDL.Func([], [IDL.Nat], []),
    'getUserPersonalInfo' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserPersonalInfo)],
        ['query'],
      ),
    'getUserPixelBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjectCount' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'getUsersByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserPersonalInfo))],
        [],
      ),
    'getUsersWithCompleteInfo' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserPersonalInfo))],
        [],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeDemoUserProfile' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listAllKnownUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'listAllUsersWithPersonalInfo' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserPersonalInfo))],
        ['query'],
      ),
    'listOwnedCustomers' : IDL.Func([], [IDL.Vec(OwnedCanister)], []),
    'listPendingPixelPurchases' : IDL.Func(
        [],
        [IDL.Vec(PixelPurchase)],
        ['query'],
      ),
    'listProjects' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ProjectMetadata))],
        [],
      ),
    'newProject' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [ProjectResult], []),
    'recordEditorVisit' : IDL.Func([], [], []),
    'recordPixelPurchase' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'removeOwnedCustomer' : IDL.Func([IDL.Principal], [], []),
    'requestControllerAccess' : IDL.Func([], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePersonalInfo' : IDL.Func([UserPersonalInfo], [], []),
    'searchUsersByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserPersonalInfo))],
        [],
      ),
    'setCurrentEra' : IDL.Func([IDL.Text], [], []),
    'setCyclesThresholds' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'testAdminImport' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'topUpCanisterCycles' : IDL.Func([IDL.Nat], [CycleTopUpResult], []),
    'topUpFrontendCanisterCycles' : IDL.Func([IDL.Nat], [CycleTopUpResult], []),
    'transferICP' : IDL.Func(
        [AccountIdentifier, IDL.Nat64, IDL.Opt(IDL.Nat64)],
        [IDL.Variant({ 'ok' : IDL.Nat64, 'err' : IDL.Text })],
        [],
      ),
    'updateOwnedCustomer' : IDL.Func([IDL.Principal, OwnedCanister], [], []),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8)],
        [ProjectResult],
        [],
      ),
    'verifyIcpPayment' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Nat],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };