/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface OwnedCanister {
    userName: string;
    created: Time;
    modified: Time;
    owner: Principal;
    canisterId: Principal;
}
export interface PixelPurchase {
    status: PurchaseStatus;
    txIndex: bigint;
    createdAt: Time;
    pixels: bigint;
    amountE8s: bigint;
    buyer: Principal;
}
export interface ProjectMetadata {
    created: Time;
    modified: Time;
    name: string;
    size: bigint;
    version: bigint;
}
export interface UserPersonalInfo {
    name: string;
    email: string;
    additional?: string;
}
export type ProjectResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type AccountIdentifier = Uint8Array;
export interface CycleInfo {
    balance: bigint;
    healthStatus: HealthStatus;
}
export type CycleCheckResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type CycleTopUpResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface UserProfile {
    name: string;
}
export interface Project {
    id: string;
    owner: Principal;
    metadata: ProjectMetadata;
    data: Uint8Array;
}
export enum HealthStatus {
    ok = "ok",
    low = "low",
    critical = "critical"
}
export enum PurchaseStatus {
    pending = "pending",
    credited = "credited"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addOwnedCustomer(customer: OwnedCanister): Promise<void>;
    adminBanUser(user: Principal): Promise<void>;
    adminCreditPixels(user: Principal, amount: bigint, reason: string): Promise<bigint>;
    adminCreditPixelsForPurchase(txIndex: bigint, reason: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminRemovePixels(user: Principal, amount: bigint, reason: string): Promise<bigint>;
    adminUnbanUser(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteProject(projectId: string): Promise<ProjectResult>;
    getAdminUserOverview(): Promise<Array<{
        principal: Principal;
        name?: string;
        email?: string;
        pixels: bigint;
    }>>;
    getAllUserPixelBalances(): Promise<Array<[Principal, bigint]>>;
    getAllUsersWithPersonalInfo(): Promise<Array<[Principal, {
            name: string;
            email: string;
            additional?: string;
        }]>>;
    getCallerAccountIdentifier(): Promise<string>;
    getCallerICPBalance(): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCallerPixelBalance(): Promise<bigint>;
    getCallerPrincipal(): Promise<Principal>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCanisterCycleInfo(): Promise<CycleInfo | null>;
    getCanisterCycles(): Promise<CycleCheckResult>;
    getCanisterHealthStatus(): Promise<HealthStatus>;
    getCurrentEra(): Promise<string>;
    getEditorVisitCount(): Promise<bigint>;
    getMyPendingPixelPurchases(): Promise<Array<PixelPurchase>>;
    getOwnedCustomerByCanister(canisterId: Principal): Promise<OwnedCanister | null>;
    getOwnedCustomersByUser(user: Principal): Promise<Array<OwnedCanister>>;
    getPersonalInfo(): Promise<UserPersonalInfo | null>;
    getPixelPrice(): Promise<bigint>;
    getProject(projectId: string): Promise<Project | null>;
    getRealBackendCycleInfo(): Promise<CycleInfo | null>;
    getRealFrontendCycleInfo(): Promise<CycleInfo | null>;
    getTotalPixelsSold(): Promise<bigint>;
    getTotalProjectCount(): Promise<bigint>;
    getUserPersonalInfo(user: Principal): Promise<UserPersonalInfo | null>;
    getUserPixelBalance(user: Principal): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProjectCount(user: Principal): Promise<bigint>;
    getUsersByName(name: string): Promise<Array<[Principal, UserPersonalInfo]>>;
    getUsersWithCompleteInfo(): Promise<Array<[Principal, UserPersonalInfo]>>;
    initializeAccessControl(): Promise<void>;
    initializeDemoUserProfile(arg0: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isUserBanned(user: Principal): Promise<boolean>;
    listAllKnownUsers(): Promise<Array<Principal>>;
    listAllUsers(): Promise<Array<Principal>>;
    listAllUsersWithPersonalInfo(): Promise<Array<[Principal, UserPersonalInfo]>>;
    listOwnedCustomers(): Promise<Array<OwnedCanister>>;
    listPendingPixelPurchases(): Promise<Array<PixelPurchase>>;
    listProjects(): Promise<Array<[string, ProjectMetadata]>>;
    newProject(name: string, data: Uint8Array): Promise<ProjectResult>;
    recordEditorVisit(): Promise<void>;
    recordPixelPurchase(txIndex: bigint, pixels: bigint, amountE8s: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeOwnedCustomer(canisterId: Principal): Promise<void>;
    requestControllerAccess(): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePersonalInfo(personalInfo: UserPersonalInfo): Promise<void>;
    searchUsersByEmail(email: string): Promise<Array<[Principal, UserPersonalInfo]>>;
    setCurrentEra(era: string): Promise<void>;
    setCyclesThresholds(okThreshold: bigint, lowThreshold: bigint, criticalThreshold: bigint): Promise<void>;
    testAdminImport(testAmount: bigint): Promise<string>;
    topUpCanisterCycles(amount: bigint): Promise<CycleTopUpResult>;
    topUpFrontendCanisterCycles(amount: bigint): Promise<CycleTopUpResult>;
    transferICP(toAccountId: AccountIdentifier, amountE8s: bigint, memo: bigint | null): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateOwnedCustomer(canisterId: Principal, updatedCustomer: OwnedCanister): Promise<void>;
    updateProject(projectId: string, data: Uint8Array): Promise<ProjectResult>;
    verifyIcpPayment(txIndex: bigint, buyer: Principal, amountE8s: bigint): Promise<boolean>;
}
import type { CycleCheckResult as _CycleCheckResult, CycleInfo as _CycleInfo, CycleTopUpResult as _CycleTopUpResult, HealthStatus as _HealthStatus, OwnedCanister as _OwnedCanister, PixelPurchase as _PixelPurchase, Project as _Project, ProjectResult as _ProjectResult, PurchaseStatus as _PurchaseStatus, Time as _Time, UserPersonalInfo as _UserPersonalInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOwnedCustomer(arg0: OwnedCanister): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOwnedCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOwnedCustomer(arg0);
            return result;
        }
    }
    async adminBanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBanUser(arg0);
            return result;
        }
    }
    async adminCreditPixels(arg0: Principal, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreditPixels(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreditPixels(arg0, arg1, arg2);
            return result;
        }
    }
    async adminCreditPixelsForPurchase(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreditPixelsForPurchase(arg0, arg1);
                return from_candid_variant_n1(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreditPixelsForPurchase(arg0, arg1);
            return from_candid_variant_n1(this.uploadFile, this.downloadFile, result);
        }
    }
    async adminRemovePixels(arg0: Principal, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemovePixels(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemovePixels(arg0, arg1, arg2);
            return result;
        }
    }
    async adminUnbanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnbanUser(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<ProjectResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return from_candid_ProjectResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return from_candid_ProjectResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminUserOverview(): Promise<Array<{
        principal: Principal;
        name?: string;
        email?: string;
        pixels: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUserOverview();
                return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUserOverview();
            return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllUserPixelBalances(): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserPixelBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserPixelBalances();
            return result;
        }
    }
    async getAllUsersWithPersonalInfo(): Promise<Array<[Principal, {
            name: string;
            email: string;
            additional?: string;
        }]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWithPersonalInfo();
                return from_candid_vec_n9(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWithPersonalInfo();
            return from_candid_vec_n9(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerAccountIdentifier(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAccountIdentifier();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAccountIdentifier();
            return result;
        }
    }
    async getCallerICPBalance(): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerICPBalance();
                return from_candid_variant_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerICPBalance();
            return from_candid_variant_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerPixelBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPixelBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPixelBalance();
            return result;
        }
    }
    async getCallerPrincipal(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPrincipal();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCanisterCycleInfo(): Promise<CycleInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterCycleInfo();
                return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterCycleInfo();
            return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCanisterCycles(): Promise<CycleCheckResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterCycles();
                return from_candid_CycleCheckResult_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterCycles();
            return from_candid_CycleCheckResult_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCanisterHealthStatus(): Promise<HealthStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterHealthStatus();
                return from_candid_HealthStatus_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterHealthStatus();
            return from_candid_HealthStatus_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCurrentEra(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentEra();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentEra();
            return result;
        }
    }
    async getEditorVisitCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getEditorVisitCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEditorVisitCount();
            return result;
        }
    }
    async getMyPendingPixelPurchases(): Promise<Array<PixelPurchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPendingPixelPurchases();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPendingPixelPurchases();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOwnedCustomerByCanister(arg0: Principal): Promise<OwnedCanister | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnedCustomerByCanister(arg0);
                return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnedCustomerByCanister(arg0);
            return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOwnedCustomersByUser(arg0: Principal): Promise<Array<OwnedCanister>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnedCustomersByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnedCustomersByUser(arg0);
            return result;
        }
    }
    async getPersonalInfo(): Promise<UserPersonalInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalInfo();
                return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalInfo();
            return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPixelPrice(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPixelPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPixelPrice();
            return result;
        }
    }
    async getProject(arg0: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRealBackendCycleInfo(): Promise<CycleInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRealBackendCycleInfo();
                return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRealBackendCycleInfo();
            return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRealFrontendCycleInfo(): Promise<CycleInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRealFrontendCycleInfo();
                return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRealFrontendCycleInfo();
            return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTotalPixelsSold(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalPixelsSold();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalPixelsSold();
            return result;
        }
    }
    async getTotalProjectCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalProjectCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalProjectCount();
            return result;
        }
    }
    async getUserPersonalInfo(arg0: Principal): Promise<UserPersonalInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPersonalInfo(arg0);
                return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPersonalInfo(arg0);
            return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserPixelBalance(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPixelBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPixelBalance(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProjectCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProjectCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProjectCount(arg0);
            return result;
        }
    }
    async getUsersByName(arg0: string): Promise<Array<[Principal, UserPersonalInfo]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersByName(arg0);
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersByName(arg0);
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUsersWithCompleteInfo(): Promise<Array<[Principal, UserPersonalInfo]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersWithCompleteInfo();
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersWithCompleteInfo();
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async initializeDemoUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDemoUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDemoUserProfile(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserBanned(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserBanned(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserBanned(arg0);
            return result;
        }
    }
    async listAllKnownUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllKnownUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllKnownUsers();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return result;
        }
    }
    async listAllUsersWithPersonalInfo(): Promise<Array<[Principal, UserPersonalInfo]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsersWithPersonalInfo();
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsersWithPersonalInfo();
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async listOwnedCustomers(): Promise<Array<OwnedCanister>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOwnedCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOwnedCustomers();
            return result;
        }
    }
    async listPendingPixelPurchases(): Promise<Array<PixelPurchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingPixelPurchases();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingPixelPurchases();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<[string, ProjectMetadata]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return result;
        }
    }
    async newProject(arg0: string, arg1: Uint8Array): Promise<ProjectResult> {
        if (this.processError) {
            try {
                const result = await this.actor.newProject(arg0, arg1);
                return from_candid_ProjectResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.newProject(arg0, arg1);
            return from_candid_ProjectResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async recordEditorVisit(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordEditorVisit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordEditorVisit();
            return result;
        }
    }
    async recordPixelPurchase(arg0: bigint, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPixelPurchase(arg0, arg1, arg2);
                return from_candid_variant_n5(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPixelPurchase(arg0, arg1, arg2);
            return from_candid_variant_n5(this.uploadFile, this.downloadFile, result);
        }
    }
    async removeOwnedCustomer(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeOwnedCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeOwnedCustomer(arg0);
            return result;
        }
    }
    async requestControllerAccess(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestControllerAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestControllerAccess();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePersonalInfo(arg0: UserPersonalInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePersonalInfo(to_candid_UserPersonalInfo_n33(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePersonalInfo(to_candid_UserPersonalInfo_n33(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async searchUsersByEmail(arg0: string): Promise<Array<[Principal, UserPersonalInfo]>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsersByEmail(arg0);
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsersByEmail(arg0);
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async setCurrentEra(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCurrentEra(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCurrentEra(arg0);
            return result;
        }
    }
    async setCyclesThresholds(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCyclesThresholds(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCyclesThresholds(arg0, arg1, arg2);
            return result;
        }
    }
    async testAdminImport(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.testAdminImport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testAdminImport(arg0);
            return result;
        }
    }
    async topUpCanisterCycles(arg0: bigint): Promise<CycleTopUpResult> {
        if (this.processError) {
            try {
                const result = await this.actor.topUpCanisterCycles(arg0);
                return from_candid_CycleTopUpResult_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.topUpCanisterCycles(arg0);
            return from_candid_CycleTopUpResult_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async topUpFrontendCanisterCycles(arg0: bigint): Promise<CycleTopUpResult> {
        if (this.processError) {
            try {
                const result = await this.actor.topUpFrontendCanisterCycles(arg0);
                return from_candid_CycleTopUpResult_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.topUpFrontendCanisterCycles(arg0);
            return from_candid_CycleTopUpResult_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async transferICP(arg0: AccountIdentifier, arg1: bigint, arg2: bigint | null): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.transferICP(arg0, arg1, to_candid_opt_n36(this.uploadFile, this.downloadFile, arg2));
                return from_candid_variant_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferICP(arg0, arg1, to_candid_opt_n36(this.uploadFile, this.downloadFile, arg2));
            return from_candid_variant_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async updateOwnedCustomer(arg0: Principal, arg1: OwnedCanister): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOwnedCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOwnedCustomer(arg0, arg1);
            return result;
        }
    }
    async updateProject(arg0: string, arg1: Uint8Array): Promise<ProjectResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1);
                return from_candid_ProjectResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1);
            return from_candid_ProjectResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async verifyIcpPayment(arg0: bigint, arg1: Principal, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyIcpPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyIcpPayment(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_CycleCheckResult_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleCheckResult): CycleCheckResult {
    return from_candid_variant_n1(uploadFile, downloadFile, value);
}
function from_candid_CycleInfo_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleInfo): CycleInfo {
    return from_candid_record_n18(uploadFile, downloadFile, value);
}
function from_candid_CycleTopUpResult_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleTopUpResult): CycleTopUpResult {
    return from_candid_variant_n1(uploadFile, downloadFile, value);
}
function from_candid_HealthStatus_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthStatus): HealthStatus {
    return from_candid_variant_n20(uploadFile, downloadFile, value);
}
function from_candid_PixelPurchase_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PixelPurchase): PixelPurchase {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_ProjectResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectResult): ProjectResult {
    return from_candid_variant_n5(uploadFile, downloadFile, value);
}
function from_candid_PurchaseStatus_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseStatus): PurchaseStatus {
    return from_candid_variant_n26(uploadFile, downloadFile, value);
}
function from_candid_UserPersonalInfo_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPersonalInfo): UserPersonalInfo {
    return from_candid_record_n11(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(uploadFile, downloadFile, value);
}
function from_candid_opt_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CycleInfo]): CycleInfo | null {
    return value.length === 0 ? null : from_candid_CycleInfo_n17(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OwnedCanister]): OwnedCanister | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPersonalInfo]): UserPersonalInfo | null {
    return value.length === 0 ? null : from_candid_UserPersonalInfo_n29(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    additional: [] | [string];
}): {
    name: string;
    email: string;
    additional?: string;
} {
    return {
        name: value.name,
        email: value.email,
        additional: record_opt_to_undefined(from_candid_opt_n8(uploadFile, downloadFile, value.additional))
    };
}
function from_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: bigint;
    healthStatus: _HealthStatus;
}): {
    balance: bigint;
    healthStatus: HealthStatus;
} {
    return {
        balance: value.balance,
        healthStatus: from_candid_HealthStatus_n19(uploadFile, downloadFile, value.healthStatus)
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PurchaseStatus;
    txIndex: bigint;
    createdAt: _Time;
    pixels: bigint;
    amountE8s: bigint;
    buyer: Principal;
}): {
    status: PurchaseStatus;
    txIndex: bigint;
    createdAt: Time;
    pixels: bigint;
    amountE8s: bigint;
    buyer: Principal;
} {
    return {
        status: from_candid_PurchaseStatus_n25(uploadFile, downloadFile, value.status),
        txIndex: value.txIndex,
        createdAt: value.createdAt,
        pixels: value.pixels,
        amountE8s: value.amountE8s,
        buyer: value.buyer
    };
}
function from_candid_record_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: [] | [string];
    email: [] | [string];
    pixels: bigint;
}): {
    principal: Principal;
    name?: string;
    email?: string;
    pixels: bigint;
} {
    return {
        principal: value.principal,
        name: record_opt_to_undefined(from_candid_opt_n8(uploadFile, downloadFile, value.name)),
        email: record_opt_to_undefined(from_candid_opt_n8(uploadFile, downloadFile, value.email)),
        pixels: value.pixels
    };
}
function from_candid_tuple_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, {
        name: string;
        email: string;
        additional: [] | [string];
    }]): [Principal, {
        name: string;
        email: string;
        additional?: string;
    }] {
    return [
        value[0],
        from_candid_record_n11(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_tuple_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserPersonalInfo]): [Principal, UserPersonalInfo] {
    return [
        value[0],
        from_candid_UserPersonalInfo_n29(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    low: null;
} | {
    critical: null;
}): HealthStatus {
    return "ok" in value ? HealthStatus.ok : "low" in value ? HealthStatus.low : "critical" in value ? HealthStatus.critical : value;
}
function from_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    credited: null;
}): PurchaseStatus {
    return "pending" in value ? PurchaseStatus.pending : "credited" in value ? PurchaseStatus.credited : value;
}
function from_candid_variant_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PixelPurchase>): Array<PixelPurchase> {
    return value.map((x)=>from_candid_PixelPurchase_n23(uploadFile, downloadFile, x));
}
function from_candid_vec_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserPersonalInfo]>): Array<[Principal, UserPersonalInfo]> {
    return value.map((x)=>from_candid_tuple_n32(uploadFile, downloadFile, x));
}
function from_candid_vec_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    principal: Principal;
    name: [] | [string];
    email: [] | [string];
    pixels: bigint;
}>): Array<{
    principal: Principal;
    name?: string;
    email?: string;
    pixels: bigint;
}> {
    return value.map((x)=>from_candid_record_n7(uploadFile, downloadFile, x));
}
function from_candid_vec_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, {
        name: string;
        email: string;
        additional: [] | [string];
    }]>): Array<[Principal, {
        name: string;
        email: string;
        additional?: string;
    }]> {
    return value.map((x)=>from_candid_tuple_n10(uploadFile, downloadFile, x));
}
function to_candid_UserPersonalInfo_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPersonalInfo): _UserPersonalInfo {
    return to_candid_record_n34(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    additional?: string;
}): {
    name: string;
    email: string;
    additional: [] | [string];
} {
    return {
        name: value.name,
        email: value.email,
        additional: value.additional ? candid_some(value.additional) : candid_none()
    };
}
function to_candid_variant_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
